name: Test

on:
  push:
    paths:
      - "**/*.py"
      - "pyproject.toml"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -e ".[testing]"

      - name: Run tests
        run: pytest
